org: ekedani
service: serverless-functions-practice

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.helloWorld
  todos:
    handler: handler.todos
    events:
      - http:
          path: todos/{proxy+}
          method: any

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

build:
  esbuild: false # Serverless includes ESBuild out-of-the box, but it conflicts with the required plugin

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-esbuild

custom:
  serverless-dynamodb:
    start:
      port: 8000
      docker: false
      migrate: true