org: ekedani
service: serverless-functions-practice

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello


plugins:
  - serverless-offline
  - serverless-esbuild