org: ekedani
service: serverless-functions-practice

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello

build:
  esbuild: false
  
plugins:
  - serverless-offline
  - serverless-esbuild